export interface ServiceFeature {
  title: string;
  desc: string;
}

export interface ServiceFaq {
  q: string;
  a: string;
}

export interface ServiceData {
  slug: string;
  title: string;
  tagline: string;
  description: string;
  heroGradient: string;
  accentColor: string;
  badgeColor: string;
  icon: string;
  stats: { value: string; label: string }[];
  offerings: ServiceFeature[];
  techStack: { category: string; items: string[] }[];
  process: { step: string; title: string; desc: string }[];
  benefits: string[];
  faqs: ServiceFaq[];
  caseStudy: {
    title: string;
    industry: string;
    challenge: string;
    solution: string;
    results: string[];
  };
}

export const servicesData: ServiceData[] = [
  {
    slug: "web-development",
    title: "Web Development",
    tagline: "Fast, scalable, and pixel-perfect web applications",
    description:
      "We build modern web applications from simple marketing sites to complex SaaS platforms — using the latest frameworks, performance best practices, and clean architecture that scales.",
    heroGradient: "from-indigo-600 via-purple-700 to-indigo-900",
    accentColor: "indigo",
    badgeColor: "text-indigo-300 border-indigo-500/30",
    icon: "🌐",
    stats: [
      { value: "80+", label: "Web Apps Delivered" },
      { value: "<1s", label: "Average Load Time" },
      { value: "100/100", label: "Lighthouse Score" },
      { value: "5yr", label: "Avg Product Lifespan" },
    ],
    offerings: [
      { title: "SaaS Product Development", desc: "Multi-tenant SaaS platforms with subscription billing, role-based access, usage analytics, and onboarding flows." },
      { title: "Progressive Web Apps (PWA)", desc: "Offline-capable, installable web apps with native-like performance on any device." },
      { title: "Admin Dashboards & Portals", desc: "Data-rich admin panels with complex tables, charts, filters, bulk actions, and real-time updates." },
      { title: "Landing Pages & Marketing Sites", desc: "High-converting landing pages with A/B testing hooks, SEO structure, and CMS integration." },
      { title: "CMS-Powered Websites", desc: "Headless CMS setups with Sanity, Contentful, or Strapi — editors update content without touching code." },
      { title: "Real-Time Web Apps", desc: "WebSocket-powered features: live dashboards, chat, notifications, collaborative editing." },
      { title: "API-First Architecture", desc: "Decoupled frontend and backend for flexibility, testability, and easy future expansion." },
      { title: "Web Performance Optimisation", desc: "Core Web Vitals tuning, code splitting, lazy loading, CDN configuration, and image optimisation." },
    ],
    techStack: [
      { category: "Frontend", items: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Framer Motion"] },
      { category: "Backend", items: ["Node.js", "Express", "NestJS", "Python", "Go"] },
      { category: "Database", items: ["PostgreSQL", "MongoDB", "Redis", "Supabase"] },
      { category: "Infrastructure", items: ["Vercel", "AWS", "Docker", "Cloudflare"] },
      { category: "CMS", items: ["Sanity", "Contentful", "Strapi", "Payload"] },
    ],
    process: [
      { step: "01", title: "Discovery", desc: "Understand your users, goals, and constraints. Produce a detailed scope and architecture proposal." },
      { step: "02", title: "Design", desc: "Figma wireframes and high-fidelity mockups. Full design system and responsive layouts." },
      { step: "03", title: "Development", desc: "Agile sprints with weekly demos. TypeScript-first, tested, reviewed code." },
      { step: "04", title: "Testing", desc: "Unit, integration, E2E tests. Cross-browser, accessibility, and performance audits." },
      { step: "05", title: "Deployment", desc: "CI/CD pipeline setup. Zero-downtime deployment with rollback strategy." },
      { step: "06", title: "Growth", desc: "Analytics integration, A/B testing support, and ongoing feature development." },
    ],
    benefits: [
      "SEO-optimised from day one",
      "WCAG 2.1 accessibility compliant",
      "Core Web Vitals optimised",
      "Mobile-first responsive design",
      "Secure by default (OWASP Top 10)",
      "Complete source code ownership",
    ],
    faqs: [
      { q: "How long does a typical web app take?", a: "A simple marketing site takes 2–3 weeks. A full SaaS product typically takes 8–16 weeks depending on complexity." },
      { q: "Do you use templates or build from scratch?", a: "We always build custom. Every project is designed and engineered specifically for your product and brand." },
      { q: "Can you work with our existing design?", a: "Absolutely. We can take Figma files, Zeplin exports, or even rough sketches and turn them into production code." },
      { q: "Will the site be fast on mobile?", a: "Yes. We use mobile-first design, Next.js image optimisation, and server-side rendering to ensure fast loads everywhere." },
    ],
    caseStudy: {
      title: "EduLaunch LMS",
      industry: "EdTech",
      challenge: "An edtech startup needed a real-time learning platform to support 100,000 concurrent students with live classes, quizzes, and progress tracking.",
      solution: "Built a Next.js + WebSocket platform with adaptive quiz engine, video integration, and a live dashboard for teachers. Used Redis for session management and CDN-cached assets.",
      results: ["100,000+ concurrent users supported", "Page load time under 1.2s globally", "99.9% uptime since launch", "38% increase in course completion rates"],
    },
  },

  {
    slug: "mobile-app-development",
    title: "Mobile App Development",
    tagline: "Native & cross-platform apps users love",
    description:
      "We build iOS and Android apps that feel native, perform brilliantly, and are engineered to scale — using React Native and Flutter for cross-platform, or Swift/Kotlin for pure native.",
    heroGradient: "from-purple-600 via-pink-700 to-rose-900",
    accentColor: "purple",
    badgeColor: "text-purple-300 border-purple-500/30",
    icon: "📱",
    stats: [
      { value: "40+", label: "Apps Published" },
      { value: "4.8★", label: "Avg App Store Rating" },
      { value: "5M+", label: "End Users Served" },
      { value: "12wk", label: "Avg MVP Timeline" },
    ],
    offerings: [
      { title: "Cross-Platform (React Native / Flutter)", desc: "One codebase, two stores. Share 90%+ of code while achieving near-native performance and UX." },
      { title: "Native iOS (Swift)", desc: "Pure Swift apps that leverage the full Apple ecosystem — SwiftUI, ARKit, HealthKit, CoreML." },
      { title: "Native Android (Kotlin)", desc: "Kotlin-first Android apps with Jetpack Compose, Material 3, and deep Android integration." },
      { title: "Offline-First Apps", desc: "Apps that work without internet using local SQLite/Realm storage and intelligent sync strategies." },
      { title: "Real-Time Features", desc: "Chat, live tracking, push notifications, WebSocket feeds, and collaborative features." },
      { title: "App Store Optimisation", desc: "ASO strategy, screenshot design, metadata optimisation, and review management." },
      { title: "Existing App Modernisation", desc: "Refactor legacy Objective-C/Java apps to modern Swift/Kotlin or migrate to cross-platform." },
      { title: "Wearable & IoT Integration", desc: "Apple Watch, WearOS, Bluetooth BLE device pairing, and sensor data processing." },
    ],
    techStack: [
      { category: "Cross-Platform", items: ["React Native", "Flutter", "Expo", "Capacitor"] },
      { category: "Native iOS", items: ["Swift", "SwiftUI", "UIKit", "Xcode"] },
      { category: "Native Android", items: ["Kotlin", "Jetpack Compose", "Android Studio"] },
      { category: "Backend", items: ["Firebase", "Node.js", "GraphQL", "REST APIs"] },
      { category: "State Management", items: ["Redux Toolkit", "Zustand", "Riverpod", "TanStack Query"] },
    ],
    process: [
      { step: "01", title: "Product Definition", desc: "Define user journeys, screen flows, and feature scope. Produce clickable Figma prototype." },
      { step: "02", title: "Architecture", desc: "Choose platform strategy (native vs cross-platform), plan state management and offline sync." },
      { step: "03", title: "Sprint Development", desc: "2-week sprints with TestFlight/Play Console builds every sprint for your team to test." },
      { step: "04", title: "QA & Device Testing", desc: "Test on 20+ real devices. Memory, battery, network, and crash testing." },
      { step: "05", title: "Store Submission", desc: "Handle App Store and Google Play submission, review response, and listing optimisation." },
      { step: "06", title: "Post-Launch", desc: "Crash monitoring with Sentry, analytics, feature flags, and OTA update strategy." },
    ],
    benefits: [
      "Single codebase for iOS & Android (React Native/Flutter)",
      "Offline support built in",
      "App Store & Play Store submission handled",
      "Crash monitoring from day one",
      "Deep link & push notification support",
      "GDPR & App Store privacy policy compliant",
    ],
    faqs: [
      { q: "Should I go native or cross-platform?", a: "For most products, React Native or Flutter is the right choice — it cuts cost by 40% while delivering 95% of native performance. We'll recommend based on your specific needs." },
      { q: "Do you handle App Store rejection?", a: "Yes. We follow Apple and Google guidelines carefully and handle any review rejections as part of the project." },
      { q: "Can you add the app to our existing backend?", a: "Absolutely. We integrate with any REST or GraphQL API and can also build the backend if needed." },
      { q: "How do you handle app updates after launch?", a: "We set up CI/CD pipelines so new versions can be released quickly. We also offer retainer packages for ongoing development." },
    ],
    caseStudy: {
      title: "MediConnect Telemedicine App",
      industry: "HealthTech",
      challenge: "A healthcare startup needed a HIPAA-compliant telemedicine app connecting patients with doctors through video calls, e-prescriptions, and appointment booking.",
      solution: "Built with React Native for iOS and Android. Integrated WebRTC for video calls, Stripe for payments, and a custom scheduling engine. Full HIPAA compliance with end-to-end encryption.",
      results: ["50,000+ active patients in 6 months", "4.9 stars on App Store", "Average call connection time under 3 seconds", "Zero security incidents since launch"],
    },
  },

  {
    slug: "ai-machine-learning",
    title: "AI & Machine Learning",
    tagline: "Intelligent systems that learn, predict, and automate",
    description:
      "We build production-ready AI/ML systems — from LLM-powered applications and custom model training to computer vision pipelines and intelligent automation — that deliver measurable business value.",
    heroGradient: "from-cyan-600 via-blue-700 to-indigo-900",
    accentColor: "cyan",
    badgeColor: "text-cyan-300 border-cyan-500/30",
    icon: "🤖",
    stats: [
      { value: "30+", label: "AI Products Shipped" },
      { value: "94%", label: "Avg Model Accuracy" },
      { value: "70%", label: "Cost Reduction (clients)" },
      { value: "10x", label: "Automation Multiplier" },
    ],
    offerings: [
      { title: "LLM Integration & RAG Systems", desc: "GPT-4, Claude, Gemini, and open-source LLM integration with RAG pipelines for domain-specific knowledge." },
      { title: "Custom AI Chatbots", desc: "Context-aware chatbots trained on your data — for customer support, internal tools, or sales automation." },
      { title: "Computer Vision", desc: "Object detection, image classification, OCR, face recognition, and quality inspection systems." },
      { title: "Predictive Analytics", desc: "Demand forecasting, churn prediction, fraud scoring, and risk modelling with explainable outputs." },
      { title: "NLP & Text Intelligence", desc: "Sentiment analysis, entity extraction, document classification, and summarisation pipelines." },
      { title: "MLOps & Model Deployment", desc: "CI/CD for ML: model versioning, A/B testing, drift detection, and production monitoring." },
      { title: "Recommendation Engines", desc: "Collaborative and content-based filtering for product, content, and service personalisation." },
      { title: "AI Process Automation", desc: "Intelligent document processing, workflow automation, and decision support systems." },
    ],
    techStack: [
      { category: "ML Frameworks", items: ["PyTorch", "TensorFlow", "scikit-learn", "XGBoost"] },
      { category: "LLM / GenAI", items: ["OpenAI", "Anthropic Claude", "LangChain", "LlamaIndex", "Ollama"] },
      { category: "MLOps", items: ["MLflow", "Weights & Biases", "DVC", "Seldon"] },
      { category: "Data", items: ["Pandas", "Polars", "Apache Spark", "Feast"] },
      { category: "Infrastructure", items: ["AWS SageMaker", "GCP Vertex AI", "Docker", "Kubernetes"] },
    ],
    process: [
      { step: "01", title: "Problem Framing", desc: "Define the business problem as an ML task. Audit existing data. Set measurable success metrics." },
      { step: "02", title: "Data Engineering", desc: "Data collection, cleaning, feature engineering, and pipeline construction." },
      { step: "03", title: "Model Development", desc: "Experiment tracking, baseline models, iterative training, and hyperparameter tuning." },
      { step: "04", title: "Evaluation", desc: "Rigorous evaluation on held-out data. Bias audits, robustness testing, and explainability." },
      { step: "05", title: "Deployment", desc: "REST API serving, batch inference, or real-time streaming. Containerised and auto-scaling." },
      { step: "06", title: "Monitoring", desc: "Ongoing data drift detection, performance tracking, and model retraining pipelines." },
    ],
    benefits: [
      "Explainable AI — not black boxes",
      "Production-hardened, not just notebooks",
      "Model monitoring and drift detection",
      "Full data privacy and compliance",
      "Bias and fairness audits",
      "Seamless integration with existing systems",
    ],
    faqs: [
      { q: "Do I need a lot of data to start?", a: "Not always. We can use transfer learning, synthetic data, and few-shot techniques. We'll assess your data and recommend the right approach." },
      { q: "How do you prevent AI hallucinations?", a: "We use RAG architectures, grounding techniques, and confidence scoring to keep outputs factual and verifiable." },
      { q: "Can you improve an existing model?", a: "Yes. We do model audits, re-training, and architecture improvements on existing systems." },
      { q: "Who owns the trained models?", a: "You do. We transfer full ownership of all models, weights, and training code." },
    ],
    caseStudy: {
      title: "PropVision AI Valuation Engine",
      industry: "PropTech",
      challenge: "A real estate platform needed automated property valuation from listing images and metadata — replacing manual appraisals that took 48+ hours.",
      solution: "Built a multi-modal model combining CNN-based image analysis with structured data (location, size, amenities). Deployed as a low-latency REST API with confidence intervals.",
      results: ["94% accuracy vs professional appraisals", "Valuation time reduced from 48h to 2 seconds", "Saved $400K/year in appraisal costs", "Deployed to 3 countries"],
    },
  },

  {
    slug: "cloud-devops",
    title: "Cloud & DevOps",
    tagline: "Infrastructure that scales, CI/CD that ships",
    description:
      "We architect, migrate, and manage cloud infrastructure on AWS, GCP, and Azure — with full DevOps automation, Kubernetes orchestration, and 24/7 observability so your team can ship fast and sleep well.",
    heroGradient: "from-sky-600 via-cyan-700 to-blue-900",
    accentColor: "sky",
    badgeColor: "text-sky-300 border-sky-500/30",
    icon: "☁️",
    stats: [
      { value: "99.99%", label: "Uptime Achieved" },
      { value: "60%", label: "Avg Cloud Cost Saved" },
      { value: "10min", label: "Deploy Frequency" },
      { value: "3x", label: "Faster Release Cycles" },
    ],
    offerings: [
      { title: "Cloud Architecture Design", desc: "Multi-region, fault-tolerant architecture on AWS, GCP, or Azure — right-sized for your workload and budget." },
      { title: "Kubernetes & Container Orchestration", desc: "EKS, GKE, AKS cluster setup, Helm chart authoring, autoscaling, and service mesh configuration." },
      { title: "CI/CD Pipeline Engineering", desc: "GitHub Actions, GitLab CI, Jenkins, and ArgoCD pipelines with automated testing, staging, and rollback." },
      { title: "Infrastructure as Code (IaC)", desc: "Terraform and Pulumi modules for reproducible, version-controlled infrastructure." },
      { title: "Cloud Cost Optimisation", desc: "Right-sizing, reserved instance analysis, spot instance strategies, and FinOps dashboards." },
      { title: "Observability Stack", desc: "Prometheus, Grafana, Datadog, or CloudWatch with alerting, SLOs, and incident runbooks." },
      { title: "Cloud Migration", desc: "Lift-and-shift, re-platforming, and full re-architecture migrations with zero-downtime cutover plans." },
      { title: "Disaster Recovery & Backup", desc: "RTO/RPO-driven DR strategy, automated backups, cross-region replication, and failover testing." },
    ],
    techStack: [
      { category: "Cloud", items: ["AWS", "Google Cloud", "Microsoft Azure", "Cloudflare"] },
      { category: "Containers", items: ["Docker", "Kubernetes", "Helm", "Istio"] },
      { category: "IaC", items: ["Terraform", "Pulumi", "AWS CDK", "Ansible"] },
      { category: "CI/CD", items: ["GitHub Actions", "GitLab CI", "ArgoCD", "Jenkins"] },
      { category: "Observability", items: ["Prometheus", "Grafana", "Datadog", "PagerDuty"] },
    ],
    process: [
      { step: "01", title: "Audit", desc: "Review current infrastructure, identify bottlenecks, security gaps, and cost inefficiencies." },
      { step: "02", title: "Architecture", desc: "Design target state architecture with detailed migration plan and risk assessment." },
      { step: "03", title: "IaC Setup", desc: "Terraform/Pulumi modules for all infrastructure. Version-controlled, peer-reviewed." },
      { step: "04", title: "Pipeline Build", desc: "CI/CD from scratch: build, test, security scan, deploy, rollback in under 10 minutes." },
      { step: "05", title: "Observability", desc: "Full metrics, logs, and traces. SLO dashboards and on-call runbooks." },
      { step: "06", title: "Handover & Support", desc: "Knowledge transfer, runbook documentation, and optional managed service." },
    ],
    benefits: [
      "Infrastructure as code — fully reproducible",
      "Auto-scaling for unpredictable traffic",
      "Zero-downtime deployments",
      "Multi-region redundancy",
      "Security hardening and compliance",
      "Cost transparency and optimisation",
    ],
    faqs: [
      { q: "Which cloud provider do you recommend?", a: "It depends on your team, workload, and existing tools. We're provider-agnostic and will recommend the best fit for you." },
      { q: "Can you manage our existing cloud setup?", a: "Yes. We offer managed DevOps services and can take over any existing AWS/GCP/Azure environment." },
      { q: "What if we want to move between cloud providers?", a: "We design multi-cloud and cloud-agnostic architectures from the start to avoid vendor lock-in." },
      { q: "Do you offer 24/7 on-call support?", a: "Yes. Our managed DevOps plans include 24/7 on-call coverage with defined SLAs." },
    ],
    caseStudy: {
      title: "LogiTrack Fleet Platform",
      industry: "Logistics",
      challenge: "A logistics company's monolithic on-premise system couldn't handle peak loads and had 6-hour maintenance windows causing $200K/month in lost revenue.",
      solution: "Migrated to Kubernetes on AWS EKS with microservices. Implemented blue-green deployments, auto-scaling groups, and a Grafana observability stack.",
      results: ["99.99% uptime since migration", "Deploy time reduced from 6 hours to 8 minutes", "Infrastructure costs down 55%", "Zero downtime deployments achieved"],
    },
  },

  {
    slug: "backend-api",
    title: "Backend & API Development",
    tagline: "Scalable APIs and microservices built to last",
    description:
      "We engineer high-performance backends — REST APIs, GraphQL, microservices, real-time systems, and event-driven architectures — that power your product reliably at any scale.",
    heroGradient: "from-emerald-600 via-teal-700 to-cyan-900",
    accentColor: "emerald",
    badgeColor: "text-emerald-300 border-emerald-500/30",
    icon: "⚙️",
    stats: [
      { value: "50ms", label: "P99 API Latency" },
      { value: "1M+", label: "Requests/min Handled" },
      { value: "99.9%", label: "API Uptime" },
      { value: "100%", label: "Test Coverage Target" },
    ],
    offerings: [
      { title: "RESTful API Design", desc: "OpenAPI-documented, versioned REST APIs following best practices for consistency, pagination, and error handling." },
      { title: "GraphQL APIs", desc: "Type-safe GraphQL schemas with DataLoader batching, subscriptions, and schema federation." },
      { title: "Microservices Architecture", desc: "Domain-driven service decomposition with well-defined contracts, service discovery, and circuit breakers." },
      { title: "Real-Time Systems", desc: "WebSocket servers, Server-Sent Events, and pub/sub systems for live data features." },
      { title: "Event-Driven Architecture", desc: "Kafka, RabbitMQ, and AWS SQS/SNS pipelines for reliable async processing and decoupling." },
      { title: "Authentication & Authorisation", desc: "OAuth 2.0, JWT, RBAC, ABAC, SSO (SAML/OIDC), and multi-factor authentication." },
      { title: "API Gateway & Rate Limiting", desc: "Kong, AWS API Gateway, or custom middleware with throttling, caching, and analytics." },
      { title: "Database Design & Optimisation", desc: "Schema design, query optimisation, indexing strategy, and connection pooling." },
    ],
    techStack: [
      { category: "Runtime", items: ["Node.js", "Go", "Python", "Java", "Rust"] },
      { category: "Frameworks", items: ["NestJS", "Fastify", "Gin", "FastAPI", "Spring Boot"] },
      { category: "Database", items: ["PostgreSQL", "MongoDB", "Redis", "ClickHouse", "Cassandra"] },
      { category: "Messaging", items: ["Apache Kafka", "RabbitMQ", "AWS SQS", "NATS"] },
      { category: "API", items: ["REST", "GraphQL", "gRPC", "WebSockets", "tRPC"] },
    ],
    process: [
      { step: "01", title: "Design", desc: "API contract design (OpenAPI/GraphQL schema), entity modelling, data flow diagrams." },
      { step: "02", title: "Architecture", desc: "Service boundaries, database selection, caching strategy, and scaling plan." },
      { step: "03", title: "Development", desc: "TDD-driven development, PR reviews, and API documentation auto-generated from code." },
      { step: "04", title: "Testing", desc: "Unit tests, integration tests, load tests (k6/Locust), and contract tests." },
      { step: "05", title: "Deployment", desc: "Blue-green or canary deployment. API versioning and deprecation strategy." },
      { step: "06", title: "Monitoring", desc: "APM tracing, error alerting, slow query detection, and capacity planning." },
    ],
    benefits: [
      "OpenAPI documentation auto-generated",
      "Comprehensive test suite included",
      "Horizontal scaling built in",
      "Structured logging and tracing",
      "Security audited before delivery",
      "SDK generation for client teams",
    ],
    faqs: [
      { q: "REST vs GraphQL — which should I use?", a: "REST is simpler and widely understood. GraphQL shines when you have many clients with different data needs. We'll recommend the right fit." },
      { q: "Can you integrate with our existing database?", a: "Yes. We work with any existing database and can optimise queries, add indexes, or plan a migration if needed." },
      { q: "How do you ensure API security?", a: "We follow OWASP API Security Top 10 — authentication, input validation, rate limiting, injection prevention, and regular security reviews." },
      { q: "Do you write tests?", a: "Yes. We target high unit and integration test coverage and run load tests to validate performance under expected traffic." },
    ],
    caseStudy: {
      title: "FinFlow Trading API",
      industry: "FinTech",
      challenge: "A trading platform needed a sub-100ms order execution API handling 50,000 concurrent users with full audit trails and strict consistency guarantees.",
      solution: "Built with Go for performance-critical paths, PostgreSQL with optimistic locking, Redis for session/cache, and Kafka for event streaming. Full OpenAPI documentation.",
      results: ["P99 latency under 45ms", "1.2M requests/min at peak", "Zero data loss incidents", "Full audit trail for regulatory compliance"],
    },
  },

  {
    slug: "cybersecurity",
    title: "Cybersecurity",
    tagline: "Security built in, not bolted on",
    description:
      "We help companies ship secure software — through penetration testing, security audits, secure code reviews, compliance consulting, and embedding security into your development lifecycle.",
    heroGradient: "from-red-600 via-orange-700 to-rose-900",
    accentColor: "red",
    badgeColor: "text-red-300 border-red-500/30",
    icon: "🛡️",
    stats: [
      { value: "500+", label: "Vulnerabilities Found" },
      { value: "0", label: "Post-Audit Breaches" },
      { value: "100%", label: "Compliance Rate" },
      { value: "24hr", label: "Report Turnaround" },
    ],
    offerings: [
      { title: "Web Application Penetration Testing", desc: "OWASP Top 10-aligned manual and automated pen testing of your web apps and APIs." },
      { title: "Mobile App Security Testing", desc: "OWASP MASVS-based testing for iOS and Android apps — data storage, network, authentication, and reverse engineering resistance." },
      { title: "Cloud Security Assessment", desc: "AWS/GCP/Azure configuration review, IAM policy audit, network exposure analysis, and hardening recommendations." },
      { title: "Secure Code Review", desc: "Manual source code review for security vulnerabilities — SAST tooling plus expert analysis." },
      { title: "Compliance Consulting", desc: "Roadmap and implementation support for PCI-DSS, ISO 27001, SOC 2, GDPR, and HIPAA." },
      { title: "Security Architecture Review", desc: "Threat modelling (STRIDE), architecture review, and security design recommendations." },
      { title: "DevSecOps Implementation", desc: "Integrate security into CI/CD: SAST, DAST, SCA, secret scanning, and container scanning." },
      { title: "Incident Response Retainer", desc: "On-call security team for breach investigation, containment, root cause analysis, and remediation." },
    ],
    techStack: [
      { category: "Pen Testing", items: ["Burp Suite", "OWASP ZAP", "Metasploit", "Nmap", "Nuclei"] },
      { category: "SAST / DAST", items: ["Semgrep", "SonarQube", "Checkmarx", "Veracode"] },
      { category: "Cloud Security", items: ["Prowler", "ScoutSuite", "CloudSploit", "Trivy"] },
      { category: "Compliance", items: ["Vanta", "Drata", "AWS Security Hub", "OpenSCAP"] },
      { category: "Monitoring", items: ["Splunk", "Elastic SIEM", "CrowdStrike", "Wazuh"] },
    ],
    process: [
      { step: "01", title: "Scoping", desc: "Define test scope, rules of engagement, environment details, and success criteria." },
      { step: "02", title: "Reconnaissance", desc: "Passive and active information gathering on targets within scope." },
      { step: "03", title: "Testing", desc: "Manual and automated vulnerability discovery across all defined attack surfaces." },
      { step: "04", title: "Exploitation", desc: "Attempt to exploit findings to determine real-world impact and severity." },
      { step: "05", title: "Reporting", desc: "Executive summary and technical report with CVSS scores, PoC, and remediation guidance." },
      { step: "06", title: "Remediation Support", desc: "Work with your dev team to fix findings. Re-test to verify fixes." },
    ],
    benefits: [
      "CREST and OSCP-certified testers",
      "Executive and technical report formats",
      "Remediation guidance included",
      "Free re-test after fixes",
      "NDA protected engagement",
      "Compliance evidence package",
    ],
    faqs: [
      { q: "Will pen testing break our production systems?", a: "We always test in a staging environment first, or schedule production testing in a maintenance window with full rollback plans." },
      { q: "How long does a pen test take?", a: "A focused web app test takes 3–5 days. A comprehensive assessment including cloud and mobile can take 2–3 weeks." },
      { q: "What format is the report?", a: "You receive an executive summary (for leadership) and a full technical report with CVSS scores, screenshots, and step-by-step remediation." },
      { q: "Do you help fix the vulnerabilities found?", a: "Yes. We provide detailed remediation guidance and are available to pair with your developers to fix critical findings." },
    ],
    caseStudy: {
      title: "FinTech Payment Platform Audit",
      industry: "FinTech",
      challenge: "A payment gateway needed a full security assessment before a PCI-DSS audit, with concerns about their custom tokenisation implementation.",
      solution: "Performed web app pen test, cloud configuration review, and secure code review of the tokenisation module. Found 2 critical, 5 high, and 12 medium vulnerabilities.",
      results: ["All critical/high findings remediated in 2 weeks", "Passed PCI-DSS Level 1 audit", "Zero findings re-opened in follow-up test", "Saved estimated $2M in potential breach costs"],
    },
  },

  {
    slug: "data-engineering",
    title: "Data Engineering & Analytics",
    tagline: "Turn raw data into decisions",
    description:
      "We design and build modern data infrastructure — pipelines, warehouses, real-time analytics, and BI dashboards — so your organisation can trust its data and act on it faster.",
    heroGradient: "from-orange-600 via-amber-700 to-yellow-900",
    accentColor: "orange",
    badgeColor: "text-orange-300 border-orange-500/30",
    icon: "📊",
    stats: [
      { value: "10TB+", label: "Data Processed Daily" },
      { value: "99%", label: "Pipeline Reliability" },
      { value: "5min", label: "Data Freshness" },
      { value: "80%", label: "Query Speed Improvement" },
    ],
    offerings: [
      { title: "Data Pipeline Engineering", desc: "Batch and streaming ETL/ELT pipelines using Airflow, dbt, Spark, and Flink." },
      { title: "Data Warehouse Design", desc: "Snowflake, BigQuery, and Redshift setup with dimensional modelling and optimised schemas." },
      { title: "Real-Time Streaming Analytics", desc: "Kafka + Flink/Spark Streaming for millisecond-latency analytics on high-volume event data." },
      { title: "BI Dashboards", desc: "Looker, Metabase, Grafana, and Tableau dashboards for business, ops, and product teams." },
      { title: "Data Lake Architecture", desc: "S3/GCS-based data lakes with Delta Lake or Apache Iceberg for reliable, queryable storage." },
      { title: "Data Quality & Governance", desc: "Great Expectations, dbt tests, and data catalogues (Datahub, OpenMetadata) for trustworthy data." },
      { title: "Reverse ETL", desc: "Sync warehouse data back to CRM, marketing, and ops tools using Census or custom pipelines." },
      { title: "Analytics Engineering", desc: "dbt model development, metrics layer setup, and self-serve analytics enablement for teams." },
    ],
    techStack: [
      { category: "Ingestion", items: ["Apache Kafka", "Fivetran", "Airbyte", "Debezium"] },
      { category: "Processing", items: ["Apache Spark", "dbt", "Apache Flink", "Airflow"] },
      { category: "Storage", items: ["Snowflake", "BigQuery", "Redshift", "Delta Lake"] },
      { category: "BI", items: ["Looker", "Metabase", "Tableau", "Grafana"] },
      { category: "Languages", items: ["SQL", "Python", "Scala", "PySpark"] },
    ],
    process: [
      { step: "01", title: "Data Audit", desc: "Map all data sources, assess quality, understand business questions that need answering." },
      { step: "02", title: "Architecture", desc: "Design data platform architecture — ingestion, storage, transformation, and serving layers." },
      { step: "03", title: "Pipeline Build", desc: "Develop and test pipelines with full data quality checks and SLA monitoring." },
      { step: "04", title: "Modelling", desc: "dbt transformation models, dimensional model design, and metrics definitions." },
      { step: "05", title: "Dashboards", desc: "Build and iterate on BI dashboards with stakeholder feedback." },
      { step: "06", title: "Operationalise", desc: "Alerting, SLA tracking, documentation, and data team enablement." },
    ],
    benefits: [
      "Single source of truth across the org",
      "Sub-5-minute data freshness",
      "Self-serve analytics for non-technical teams",
      "Data quality monitoring built in",
      "Cost-optimised storage and compute",
      "Full data lineage documentation",
    ],
    faqs: [
      { q: "We have messy data — can you still help?", a: "Yes. Messy data is the norm. We start with a data quality audit and build cleaning and standardisation into the pipelines." },
      { q: "Do you work with our existing BI tool?", a: "Yes. We work with Tableau, Power BI, Looker, Metabase, and most major BI tools." },
      { q: "How long before we see dashboards?", a: "For a focused use case, we can have initial dashboards in 2–3 weeks. Full platform builds typically take 8–12 weeks." },
      { q: "Can we access our data in real time?", a: "Yes. We design streaming pipelines that deliver data to dashboards and APIs in under 5 minutes, and sub-second where needed." },
    ],
    caseStudy: {
      title: "E-Commerce Analytics Platform",
      industry: "Retail",
      challenge: "An e-commerce company was running reports from production databases, causing slow queries and data discrepancies across 8 different spreadsheets used by 5 teams.",
      solution: "Built a Snowflake data warehouse with Fivetran ingestion, dbt transformation layer, and Metabase dashboards. Single source of truth for all KPIs.",
      results: ["Report generation time from 4 hours to 30 seconds", "Data discrepancies eliminated", "5 teams now self-serve analytics", "Revenue attribution accuracy improved by 40%"],
    },
  },

  {
    slug: "enterprise-software",
    title: "Enterprise Software",
    tagline: "Complex systems, elegantly engineered",
    description:
      "We build bespoke enterprise platforms — ERP, CRM, HRMS, workflow automation, and industry-specific systems — designed for the complexity, scale, and compliance needs of large organisations.",
    heroGradient: "from-violet-600 via-indigo-700 to-purple-900",
    accentColor: "violet",
    badgeColor: "text-violet-300 border-violet-500/30",
    icon: "🏢",
    stats: [
      { value: "25+", label: "Enterprise Clients" },
      { value: "10K+", label: "Concurrent Users" },
      { value: "5yr+", label: "Avg System Lifespan" },
      { value: "99.9%", label: "Uptime SLA" },
    ],
    offerings: [
      { title: "Custom ERP Systems", desc: "Finance, inventory, procurement, manufacturing, and reporting modules tailored to your exact workflows." },
      { title: "CRM Platforms", desc: "Custom CRM with lead management, pipeline tracking, customer 360, and sales automation." },
      { title: "HRMS & Payroll", desc: "Complete HR lifecycle: recruitment, onboarding, attendance, leave, performance, and payroll." },
      { title: "Workflow & BPM Systems", desc: "Visual workflow builders, approval chains, SLA tracking, and process automation engines." },
      { title: "Document Management", desc: "Version-controlled document repositories with audit trails, e-signatures, and role-based access." },
      { title: "Legacy System Modernisation", desc: "Re-architect monolithic legacy systems into modern, API-first microservices — with zero data loss." },
      { title: "Enterprise Integrations", desc: "SAP, Salesforce, Oracle, Workday integration via APIs, EDI, and custom middleware." },
      { title: "Multi-Tenant SaaS Platforms", desc: "White-labelled enterprise SaaS with tenant isolation, custom domains, and per-tenant configuration." },
    ],
    techStack: [
      { category: "Frontend", items: ["React", "Next.js", "Angular", "TypeScript"] },
      { category: "Backend", items: ["Java Spring Boot", "Node.js", "Go", ".NET Core"] },
      { category: "Database", items: ["PostgreSQL", "Oracle", "MSSQL", "MongoDB"] },
      { category: "Integration", items: ["Apache Camel", "MuleSoft", "REST/SOAP", "Kafka"] },
      { category: "Infrastructure", items: ["Kubernetes", "AWS", "Azure", "On-Premise"] },
    ],
    process: [
      { step: "01", title: "Requirements", desc: "Deep-dive workshops with all stakeholders. Process mapping, gap analysis, and functional spec." },
      { step: "02", title: "Architecture", desc: "System design for scale, security, and longevity. Approved by your technical and legal teams." },
      { step: "03", title: "Phased Build", desc: "Module-by-module delivery with UAT after each phase. No big-bang releases." },
      { step: "04", title: "Data Migration", desc: "ETL from legacy systems with validation, reconciliation, and rollback plans." },
      { step: "05", title: "Training & Go-Live", desc: "User training materials, admin guides, and hypercare support during go-live." },
      { step: "06", title: "Support", desc: "SLA-backed maintenance, enhancement backlog, and annual technology reviews." },
    ],
    benefits: [
      "Built for 10,000+ concurrent users",
      "Role-based access at every level",
      "Full audit log and compliance trails",
      "On-premise or private cloud deployment",
      "Integration with existing enterprise tools",
      "Comprehensive UAT and training",
    ],
    faqs: [
      { q: "How do you handle complex business logic?", a: "We run detailed process workshops with your SMEs before writing code, and use domain-driven design to model complexity correctly." },
      { q: "Can the system integrate with SAP / Oracle?", a: "Yes. We have experience with SAP BAPI/RFC, Oracle APIs, and most major enterprise systems." },
      { q: "What about data migration from our old system?", a: "Data migration is included in every enterprise project. We build ETL pipelines, validate data quality, and run parallel systems until confidence is high." },
      { q: "Do you offer on-premise deployment?", a: "Yes. We support on-premise, private cloud, hybrid, and public cloud deployments based on your compliance requirements." },
    ],
    caseStudy: {
      title: "HRNest Enterprise HRMS",
      industry: "HR Technology",
      challenge: "A 5,000-employee conglomerate was managing HR across 12 spreadsheets, 3 legacy systems, and manual payroll — causing errors, compliance risks, and 40 hours/week of manual reconciliation.",
      solution: "Built a unified HRMS covering recruitment, onboarding, attendance, leave, payroll, and performance. Integrated with existing ERP and bank payment systems.",
      results: ["40 hours/week of manual work eliminated", "Payroll errors reduced by 99%", "HR compliance audit passed first time", "Full ROI achieved in 8 months"],
    },
  },

  {
    slug: "ui-ux-design",
    title: "UI/UX Design",
    tagline: "Interfaces people enjoy using",
    description:
      "We design digital products from the user's perspective — research-led, data-informed, and crafted to convert. Every pixel serves a purpose, and every interaction is intentional.",
    heroGradient: "from-pink-600 via-rose-700 to-fuchsia-900",
    accentColor: "pink",
    badgeColor: "text-pink-300 border-pink-500/30",
    icon: "🎨",
    stats: [
      { value: "35%", label: "Avg Conversion Lift" },
      { value: "4.8★", label: "Avg Usability Score" },
      { value: "60+", label: "Products Designed" },
      { value: "50%", label: "Support Ticket Reduction" },
    ],
    offerings: [
      { title: "User Research & Discovery", desc: "User interviews, surveys, competitive analysis, and persona development to ground design in reality." },
      { title: "Information Architecture", desc: "Site maps, user flows, navigation structures, and content hierarchy to reduce cognitive load." },
      { title: "Wireframing & Prototyping", desc: "Low-fidelity wireframes to high-fidelity clickable Figma prototypes for rapid validation." },
      { title: "Visual Design & UI", desc: "Brand-aligned, pixel-perfect interface design with consistent typography, colour, and spacing." },
      { title: "Design Systems", desc: "Component libraries in Figma and code (Storybook) — one source of truth for product and engineering." },
      { title: "Mobile App UX", desc: "iOS Human Interface Guidelines and Material Design-aligned mobile UX for native feel." },
      { title: "Usability Testing", desc: "Moderated and unmoderated user testing sessions with synthesis and actionable recommendations." },
      { title: "Design-to-Dev Handoff", desc: "Developer-ready Figma with specs, assets, redlines, and interactive prototypes." },
    ],
    techStack: [
      { category: "Design", items: ["Figma", "Adobe XD", "Sketch", "Principle"] },
      { category: "Prototyping", items: ["Figma Prototypes", "ProtoPie", "Framer", "InVision"] },
      { category: "Research", items: ["Maze", "Hotjar", "UserTesting", "Optimal Workshop"] },
      { category: "Dev Handoff", items: ["Storybook", "Zeplin", "Figma Tokens", "Style Dictionary"] },
      { category: "Analytics", items: ["Mixpanel", "FullStory", "Amplitude", "Google Analytics"] },
    ],
    process: [
      { step: "01", title: "Research", desc: "User interviews, competitive audit, analytics review, and stakeholder workshops." },
      { step: "02", title: "Strategy", desc: "User personas, journey maps, problem statements, and design principles." },
      { step: "03", title: "Wireframes", desc: "Low-fidelity wireframes for key flows. Fast iteration cycles with stakeholder feedback." },
      { step: "04", title: "Visual Design", desc: "High-fidelity UI design with full design system and responsive variants." },
      { step: "05", title: "Prototype & Test", desc: "Clickable prototype, usability testing sessions, and design iteration." },
      { step: "06", title: "Handoff", desc: "Developer-ready Figma files, Storybook components, and design QA during build." },
    ],
    benefits: [
      "Research-led — not assumption-driven",
      "Accessible design (WCAG 2.1 AA)",
      "Full design system delivered",
      "Clickable prototype before development",
      "Usability tested before handoff",
      "Design QA during engineering phase",
    ],
    faqs: [
      { q: "Do you do design only, or also front-end development?", a: "We do both. Our designers and front-end engineers work together and we offer full design-to-code delivery." },
      { q: "Can you redesign an existing product?", a: "Yes. We start with a UX audit to identify friction points and opportunities, then design solutions." },
      { q: "What do we get at the end?", a: "Fully annotated Figma files, component library, design tokens, clickable prototypes, and all source assets." },
      { q: "How do you ensure designs are buildable?", a: "Our designers work closely with engineers throughout. We design with technical constraints in mind and do design QA during development." },
    ],
    caseStudy: {
      title: "FinFlow Dashboard Redesign",
      industry: "FinTech",
      challenge: "A financial analytics platform had a high-powered but confusing dashboard. Users needed 30 minutes of training to get started, and support tickets were high.",
      solution: "Conducted 20 user interviews, identified top 5 friction points, redesigned the information architecture and visual hierarchy, and built a component design system.",
      results: ["Time-to-first-insight reduced from 30min to 4min", "Support tickets down 52%", "NPS score increased from 24 to 61", "User retention up 28%"],
    },
  },

  {
    slug: "ecommerce",
    title: "E-Commerce Solutions",
    tagline: "Stores that sell, platforms that scale",
    description:
      "We build high-converting e-commerce experiences — from Shopify customisations to fully custom headless commerce platforms with advanced features, integrations, and performance at scale.",
    heroGradient: "from-teal-600 via-emerald-700 to-green-900",
    accentColor: "teal",
    badgeColor: "text-teal-300 border-teal-500/30",
    icon: "🛒",
    stats: [
      { value: "38%", label: "Avg Conversion Increase" },
      { value: "2s", label: "Target Page Load" },
      { value: "20+", label: "Stores Launched" },
      { value: "$50M+", label: "GMV Processed" },
    ],
    offerings: [
      { title: "Custom Shopify Development", desc: "Bespoke Shopify themes, custom app development, and complex liquid/API integrations." },
      { title: "Headless Commerce", desc: "Next.js storefronts with Shopify/Medusa/Commercetools backends for maximum performance and flexibility." },
      { title: "Custom E-Commerce Platforms", desc: "Fully bespoke platforms when Shopify isn't enough — multi-vendor, B2B, or complex catalogue needs." },
      { title: "Payment & Checkout Optimisation", desc: "One-click checkout, buy-now-pay-later, multi-currency, and localised payment methods." },
      { title: "Inventory & Order Management", desc: "Custom OMS, multi-warehouse inventory, dropshipping integrations, and fulfilment automation." },
      { title: "Personalisation & Recommendations", desc: "AI-driven product recommendations, dynamic pricing, and personalised homepage experiences." },
      { title: "Analytics & Conversion Optimisation", desc: "Funnel analysis, A/B testing, heatmaps, and data-driven UX optimisation." },
      { title: "Marketplace Development", desc: "Multi-vendor marketplace with seller onboarding, commission management, and escrow payments." },
    ],
    techStack: [
      { category: "Platform", items: ["Shopify Plus", "Medusa.js", "WooCommerce", "Commercetools"] },
      { category: "Frontend", items: ["Next.js", "React", "Hydrogen", "Tailwind CSS"] },
      { category: "Payments", items: ["Stripe", "Razorpay", "PayPal", "Klarna"] },
      { category: "Search", items: ["Algolia", "Elastic", "Typesense"] },
      { category: "Analytics", items: ["GA4", "Segment", "Klaviyo", "Hotjar"] },
    ],
    process: [
      { step: "01", title: "Discovery", desc: "Understand product catalogue, customer segments, and conversion goals." },
      { step: "02", title: "UX Design", desc: "Mobile-first UX design focused on conversion — PDPs, cart, and checkout flows." },
      { step: "03", title: "Development", desc: "Platform build with integrations, custom features, and performance optimisation." },
      { step: "04", title: "Testing", desc: "Cross-browser, mobile, payment flow, and load testing before launch." },
      { step: "05", title: "Launch", desc: "Zero-downtime migration, SEO redirect mapping, and launch-day monitoring." },
      { step: "06", title: "Optimise", desc: "Ongoing CRO, A/B testing, and feature development driven by analytics." },
    ],
    benefits: [
      "Mobile-first, conversion-optimised UX",
      "Core Web Vitals: all green",
      "SEO-optimised from day one",
      "Multi-currency and multi-language",
      "PCI-DSS compliant checkout",
      "Analytics and attribution tracking",
    ],
    faqs: [
      { q: "Shopify vs custom — which is right for me?", a: "Shopify is great for most brands. Custom makes sense when you need multi-vendor, complex B2B pricing, or performance beyond what Shopify allows. We'll advise." },
      { q: "Can you migrate from our current platform?", a: "Yes. We handle full data migration — products, customers, orders, and SEO redirects — with zero downtime." },
      { q: "How do you improve conversion rates?", a: "We analyse your analytics to find where users drop off, then design and A/B test improvements to checkout, PDPs, and navigation." },
      { q: "Do you integrate with our ERP/WMS?", a: "Yes. We have experience integrating Shopify and custom platforms with SAP, NetSuite, and most WMS systems." },
    ],
    caseStudy: {
      title: "ShopNest Luxury Fashion Store",
      industry: "Fashion Retail",
      challenge: "A luxury fashion brand's Shopify store was slow, generic-looking, and had a 78% cart abandonment rate. They needed a premium headless experience.",
      solution: "Built a headless Next.js storefront on Shopify Plus with custom 3D product viewer, AR try-on, personalised recommendations, and a redesigned one-click checkout.",
      results: ["Cart abandonment reduced from 78% to 41%", "Page load time improved from 5.2s to 0.9s", "38% increase in average order value", "Revenue up 62% in 3 months post-launch"],
    },
  },

  {
    slug: "qa-testing",
    title: "QA & Testing",
    tagline: "Ship with confidence, every release",
    description:
      "We build comprehensive QA strategies and automated test suites that catch bugs before users do — from unit tests and E2E automation to performance, accessibility, and security testing.",
    heroGradient: "from-amber-600 via-orange-700 to-red-900",
    accentColor: "amber",
    badgeColor: "text-amber-300 border-amber-500/30",
    icon: "✅",
    stats: [
      { value: "95%", label: "Bug Detection Rate" },
      { value: "10x", label: "Faster Release Cycles" },
      { value: "80%", label: "Test Automation Rate" },
      { value: "0", label: "P0 Bugs Post-Launch" },
    ],
    offerings: [
      { title: "Test Strategy & Planning", desc: "Risk-based test strategy, coverage planning, environment strategy, and QA process design." },
      { title: "Automated E2E Testing", desc: "Cypress and Playwright test suites for critical user journeys — run on every PR in CI." },
      { title: "API Testing Automation", desc: "Postman/Newman, REST Assured, or custom API test suites with data-driven test cases." },
      { title: "Unit & Integration Testing", desc: "Jest, Vitest, PyTest test suites with code coverage reporting and mutation testing." },
      { title: "Performance & Load Testing", desc: "k6, Locust, and JMeter load tests to validate behaviour under expected and peak traffic." },
      { title: "Mobile App Testing", desc: "Appium-based cross-device automation for iOS and Android apps on real device farms." },
      { title: "Accessibility Testing", desc: "Automated and manual WCAG 2.1 AA testing with Axe, Lighthouse, and screen reader testing." },
      { title: "Security Testing Basics", desc: "OWASP-aligned basic security tests: XSS, SQL injection, CSRF, auth bypass, and header checks." },
    ],
    techStack: [
      { category: "E2E", items: ["Cypress", "Playwright", "Selenium", "TestCafe"] },
      { category: "Unit/Integration", items: ["Jest", "Vitest", "PyTest", "JUnit", "Mocha"] },
      { category: "API Testing", items: ["Postman", "REST Assured", "Karate", "Newman"] },
      { category: "Performance", items: ["k6", "Locust", "JMeter", "Artillery"] },
      { category: "CI Integration", items: ["GitHub Actions", "GitLab CI", "Jenkins", "CircleCI"] },
    ],
    process: [
      { step: "01", title: "Audit", desc: "Review existing test coverage, identify gaps, and define quality goals." },
      { step: "02", title: "Strategy", desc: "Test pyramid design, tool selection, environment strategy, and coverage targets." },
      { step: "03", title: "Framework Setup", desc: "CI-integrated test framework, reporting dashboards, and baseline test run." },
      { step: "04", title: "Test Authoring", desc: "Write comprehensive test suites covering critical paths and edge cases." },
      { step: "05", title: "Shift Left", desc: "Embed QA in development sprint — test on every PR, not just at the end." },
      { step: "06", title: "Monitoring", desc: "Flaky test management, coverage tracking, and continuous improvement." },
    ],
    benefits: [
      "Tests run on every pull request",
      "Detailed test reports and coverage metrics",
      "Shift-left QA integrated with dev sprints",
      "Accessibility compliance verified",
      "Performance benchmarks tracked over time",
      "Reduced manual testing effort by 80%",
    ],
    faqs: [
      { q: "Should I do manual testing or automated?", a: "Both. Automation handles regression and repetitive checks. Manual testing is better for exploratory, usability, and edge case testing. We design the right mix." },
      { q: "How do you measure test quality?", a: "Code coverage, mutation score, defect escape rate, and test execution time are our key metrics." },
      { q: "Can you improve our existing flaky test suite?", a: "Yes. Fixing flaky tests is a common engagement. We audit the suite, fix root causes, and establish anti-flakiness guidelines." },
      { q: "How do you handle testing in CI/CD?", a: "We integrate test runs into your pipeline with parallelisation, failure alerts, and reporting — so broken code can't reach production." },
    ],
    caseStudy: {
      title: "FinFlow Release Automation",
      industry: "FinTech",
      challenge: "A FinTech company was releasing once a month due to fear of regressions — a 3-day manual QA cycle with 40% false negatives.",
      solution: "Built a Cypress E2E suite covering 120 critical user journeys, API test suite with 300+ test cases, and k6 load tests — all running in GitHub Actions CI.",
      results: ["Release frequency from monthly to daily", "Manual QA effort reduced by 85%", "Zero P0 regression bugs in 6 months post-automation", "Deploy confidence score: 9.4/10 from engineering team"],
    },
  },

  {
    slug: "maintenance-support",
    title: "Maintenance & Support",
    tagline: "Your product, always at its best",
    description:
      "We provide ongoing technical support, proactive monitoring, performance optimisation, security patching, and feature development — so your product stays healthy, fast, and evolving.",
    heroGradient: "from-blue-600 via-indigo-700 to-violet-900",
    accentColor: "blue",
    badgeColor: "text-blue-300 border-blue-500/30",
    icon: "🔧",
    stats: [
      { value: "<1hr", label: "Critical Issue Response" },
      { value: "99.9%", label: "Uptime Maintained" },
      { value: "24/7", label: "Monitoring Coverage" },
      { value: "50+", label: "Products Under Support" },
    ],
    offerings: [
      { title: "24/7 Production Monitoring", desc: "Uptime, error rate, latency, and infrastructure health monitoring with on-call alerting and incident response." },
      { title: "Bug Fixing & Hotfixes", desc: "SLA-backed bug fixing — critical issues addressed within 1 hour, high within 4 hours, medium within 24 hours." },
      { title: "Security Patching", desc: "Ongoing dependency updates, CVE monitoring, and proactive security patching to keep your stack safe." },
      { title: "Performance Optimisation", desc: "Continuous profiling, database query tuning, caching improvements, and load testing." },
      { title: "Feature Development Retainer", desc: "Dedicated sprint capacity for new features, UX improvements, and technical debt reduction." },
      { title: "Infrastructure Management", desc: "Cloud cost optimisation, scaling management, backup verification, and capacity planning." },
      { title: "Third-Party Integrations", desc: "Adding or updating integrations with payment gateways, CRMs, analytics tools, and APIs." },
      { title: "Quarterly Technology Reviews", desc: "Assess technical health, security posture, performance trends, and roadmap alignment." },
    ],
    techStack: [
      { category: "Monitoring", items: ["Datadog", "New Relic", "Sentry", "PagerDuty"] },
      { category: "Infrastructure", items: ["AWS", "GCP", "Terraform", "Kubernetes"] },
      { category: "Security", items: ["Dependabot", "Snyk", "OWASP ZAP", "Trivy"] },
      { category: "Performance", items: ["Lighthouse", "k6", "Grafana", "Prometheus"] },
      { category: "Communication", items: ["Slack", "Jira", "Linear", "Statuspage"] },
    ],
    process: [
      { step: "01", title: "Onboarding", desc: "Access handover, documentation review, monitoring setup, and runbook creation." },
      { step: "02", title: "Audit", desc: "Technical health check — security, performance, dependencies, and infrastructure." },
      { step: "03", title: "Monitoring", desc: "Full observability stack deployment. On-call schedule and escalation paths defined." },
      { step: "04", title: "Steady State", desc: "SLA-backed issue response, regular patching, and monthly health reports." },
      { step: "05", title: "Improvement", desc: "Proactive improvements: performance wins, security hardening, tech debt." },
      { step: "06", title: "Review", desc: "Quarterly technology reviews with recommendations for the next quarter." },
    ],
    benefits: [
      "Dedicated team who knows your codebase",
      "Proactive — we find issues before users do",
      "Transparent monthly reports",
      "Predictable monthly cost",
      "No context lost between tickets",
      "Seamless escalation to feature development",
    ],
    faqs: [
      { q: "What's included in a support SLA?", a: "Critical (system down): 1-hour response, 4-hour resolution. High: 4-hour response. Medium: 24-hour response. We define these together based on your business needs." },
      { q: "Do you need access to our source code?", a: "Yes. We require read access to source code and deployment pipelines. All access is NDA-protected and logged." },
      { q: "Can you take over support from another agency?", a: "Yes. We do this regularly. We start with a thorough technical onboarding and documentation sprint." },
      { q: "What if we want new features too?", a: "Our retainer plans include a mix of support and feature development hours. We flex between the two based on your priorities each month." },
    ],
    caseStudy: {
      title: "FinTech Payment Platform Support",
      industry: "FinTech",
      challenge: "A payment platform had no dedicated engineering support after their founding CTO left — bugs were accumulating, infrastructure was drifting, and a critical payment flow had a known intermittent bug.",
      solution: "Took over full engineering support: fixed the critical payment bug in 6 hours, set up comprehensive monitoring, cleared 40-item bug backlog in 3 weeks, and established bi-weekly feature releases.",
      results: ["Critical payment bug resolved same day", "40-item bug backlog cleared in 3 weeks", "Zero P0 incidents in 6 months", "Infrastructure costs reduced 30% through rightsizing"],
    },
  },
  {
    slug: "fintech",
    title: "FinTech Development",
    tagline: "Bank-grade software for the future of finance",
    description:
      "We specialise in high-compliance, high-performance financial technology — from payment infrastructure and lending platforms to trading systems and neobanks. We build fintech that regulators trust and users love.",
    heroGradient: "from-emerald-600 via-teal-700 to-cyan-900",
    accentColor: "emerald",
    badgeColor: "text-emerald-300 border-emerald-500/30",
    icon: "💳",
    stats: [
      { value: "$2B+", label: "Transactions Processed" },
      { value: "15+", label: "FinTech Products Shipped" },
      { value: "99.99%", label: "Uptime SLA" },
      { value: "50ms", label: "Avg API Latency" },
    ],
    offerings: [
      { title: "Payment Gateway Integration", desc: "Stripe, Razorpay, PayU, Cashfree, and custom payment flows with full PCI-DSS compliance and reconciliation." },
      { title: "KYC / AML Systems", desc: "Automated identity verification, document OCR, video KYC, liveness detection, and anti-money laundering pipelines." },
      { title: "Trading & Investment Platforms", desc: "Real-time order books, portfolio trackers, algorithmic trading engines, and SEBI-compliant apps." },
      { title: "Lending & Credit Scoring", desc: "NBFC-grade loan origination systems, bureau integrations (CIBIL/Experian), and AI-based credit models." },
      { title: "Digital Banking & Neobanks", desc: "Core banking APIs, virtual account management, UPI/IMPS/NEFT integration, and account aggregation (AA framework)." },
      { title: "Fraud Detection & Prevention", desc: "ML-powered fraud scoring, device fingerprinting, velocity checks, and real-time transaction monitoring." },
      { title: "Cross-Border Payments", desc: "Multi-currency wallets, SWIFT/SEPA integration, FX rate engines, and international remittance flows." },
      { title: "Reconciliation & Settlement", desc: "Automated ledger reconciliation, T+1/T+2 settlement engines, dispute management, and audit-ready reporting." },
    ],
    techStack: [
      { category: "Backend", items: ["Go", "Node.js", "Java Spring Boot", "Python", "Rust"] },
      { category: "Frontend", items: ["React", "Next.js", "TypeScript", "Tailwind CSS"] },
      { category: "Database", items: ["PostgreSQL", "Redis", "ClickHouse", "Cassandra"] },
      { category: "Messaging", items: ["Apache Kafka", "RabbitMQ", "AWS SQS"] },
      { category: "Compliance & Security", items: ["PCI-DSS", "ISO 27001", "RBI Guidelines", "OWASP", "Vault"] },
    ],
    process: [
      { step: "01", title: "Compliance Mapping", desc: "Map regulatory requirements (RBI, SEBI, PCI-DSS) to technical architecture before writing code." },
      { step: "02", title: "Security Architecture", desc: "Design threat model, encryption strategy, key management, and audit logging from day one." },
      { step: "03", title: "Core Build", desc: "High-performance, event-sourced backend with immutable audit trails and full test coverage." },
      { step: "04", title: "Integration", desc: "Connect payment rails, bureau APIs, banking partners, and third-party compliance services." },
      { step: "05", title: "Pen Test & Audit", desc: "External security audit, penetration testing, and compliance review before go-live." },
      { step: "06", title: "Production & Support", desc: "99.99% SLA-backed production support, real-time monitoring, and incident response." },
    ],
    benefits: [
      "RBI, SEBI, and PCI-DSS compliant architecture",
      "End-to-end encryption for all financial data",
      "Immutable audit trails on every transaction",
      "Sub-100ms payment API response time",
      "External security audit before launch",
      "24/7 SLA-backed production support",
    ],
    faqs: [
      { q: "Are you familiar with RBI regulations for NBFCs and payment aggregators?", a: "Yes. We've built for RBI-regulated NBFCs, payment aggregators, and account aggregators. We stay current with RBI circulars and build compliance into the architecture." },
      { q: "How do you handle PCI-DSS compliance?", a: "We scope the cardholder data environment carefully, use tokenisation to minimise scope, and can guide you through the SAQ or full QSA audit process." },
      { q: "Can you integrate with NPCI for UPI?", a: "Yes. We have experience with direct UPI integrations via PSP partnerships as well as indirect integrations through payment aggregators." },
      { q: "How do you ensure transaction data is secure?", a: "AES-256 encryption at rest, TLS 1.3 in transit, HSM-based key management, field-level encryption for PII, and zero-trust network architecture." },
    ],
    caseStudy: {
      title: "PayNow Lending Platform",
      industry: "NBFC / LendTech",
      challenge: "An NBFC needed a full loan origination system handling 10,000 applications/day with real-time bureau checks, automated underwriting, and RBI-compliant audit trails.",
      solution: "Built an event-sourced LOS with Go microservices, Kafka event streaming, CIBIL/Experian integration, ML-based credit scoring, and a React-based underwriter dashboard. Full RBI audit trail.",
      results: ["10,000 applications/day processed with P99 < 200ms", "Loan approval time reduced from 3 days to 4 minutes", "RBI audit passed with zero findings", "Fraud rate reduced by 68% via ML scoring"],
    },
  },
];

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return servicesData.find((s) => s.slug === slug);
}

export function getAllServiceSlugs(): string[] {
  return servicesData.map((s) => s.slug);
}
